# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025-2026  <Jochen Zeitler>
"""
A Windows desktop shortcut that opens FreeCAD straight into this workbench.

FreeCAD has no "--workbench" command-line switch, so the shortcut cannot ask
for one directly. What it can do is hand FreeCAD a script: any .FCMacro or
.py named on the command line is executed once the GUI is up. So the icon
points at FreeCAD.exe with a small generated macro as its argument, and that
macro activates the workbench.

The macro retries rather than activating once. Workbench registration is
lazy — FreeCAD discovers Mod/ directories on a timer and a workbench is not
activatable the instant the main window exists — so a single immediate call
wins or loses depending on disk speed, which is precisely the kind of bug
that only shows up on someone else's machine.

Everything here is Qt-free string and path work so it can be tested without
a GUI; ui/DesktopShortcutCommand.py runs the PowerShell this module builds.
"""

import os
import sys

WORKBENCH_NAME = "MyWorkbench"
SHORTCUT_NAME = "Chip-Packaging Workbench"
LAUNCHER_BASENAME = "DI-PASSIONATE_Launch.FCMacro"
ICON_BASENAME = "DI-PASSIONATE.ico"

# How long the macro keeps trying before giving up, in 250 ms ticks.
_ACTIVATE_RETRIES = 40


def is_windows() -> bool:
    return sys.platform.startswith("win")


# ── Where things go ───────────────────────────────────────────────────────

def desktop_dir(env=None, isdir=os.path.isdir) -> str:
    """
    The user's real Desktop.

    On a managed Windows 11 machine — which is what this workbench is
    installed on — OneDrive Known Folder Move usually redirects the Desktop
    to %OneDrive%\\Desktop, and %USERPROFILE%\\Desktop is then either absent
    or a stale empty folder nobody looks at. Writing to the wrong one puts
    the icon somewhere the user cannot see it, so prefer OneDrive's when it
    actually exists.

    env/isdir are injectable so this is testable without depending on the
    machine the tests happen to run on.
    """
    env = os.environ if env is None else env
    candidates = []
    one = env.get("OneDrive") or env.get("OneDriveCommercial") or env.get("OneDriveConsumer")
    if one:
        candidates.append(os.path.join(one, "Desktop"))
    profile = env.get("USERPROFILE") or env.get("HOME") or os.path.expanduser("~")
    candidates.append(os.path.join(profile, "Desktop"))

    for path in candidates:
        if isdir(path):
            return path
    return candidates[-1]      # nothing exists yet; the last is still the
                               # correct place to create it


def freecad_executable(bindir=None) -> str:
    """
    The GUI FreeCAD.exe, not the console one.

    sys.executable is freecadcmd.exe when running headlessly and FreeCAD.exe
    when running in the GUI, so it cannot be used directly — a shortcut
    pointing at freecadcmd.exe opens a console that exits immediately.
    """
    if bindir is None:
        try:
            import FreeCAD
            # getHomePath() ends with a separator, so a bare join yields
            # "...FreeCAD 1.1\\bin" — harmless to Windows itself but it ends
            # up visible in the shortcut's properties dialog.
            bindir = os.path.join(FreeCAD.getHomePath(), "bin")
        except Exception:
            bindir = os.path.dirname(sys.executable)
    bindir = os.path.normpath(bindir)
    names = ["FreeCAD.exe", "freecad.exe"] if is_windows() else ["FreeCAD", "freecad"]
    for name in names:
        path = os.path.join(bindir, name)
        if os.path.isfile(path):
            return path
    return os.path.join(bindir, names[0])


def workbench_root() -> str:
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def launcher_path(root=None) -> str:
    root = root or workbench_root()
    return os.path.join(root, "resources", LAUNCHER_BASENAME)


def icon_path(root=None) -> str:
    root = root or workbench_root()
    return os.path.join(root, "resources", "icons", ICON_BASENAME)


def shortcut_path(desktop=None) -> str:
    return os.path.join(desktop or desktop_dir(), f"{SHORTCUT_NAME}.lnk")


# ── The launcher macro ────────────────────────────────────────────────────

def launcher_macro_text(workbench: str = WORKBENCH_NAME,
                        retries: int = _ACTIVATE_RETRIES) -> str:
    """The script FreeCAD runs at startup to land the user in the workbench."""
    return f'''# SPDX-License-Identifier: GPL-3.0-or-later
# GENERATED by core/desktop_shortcut.py — regenerated whenever the desktop
# shortcut is (re)created. Edits here will be overwritten.
"""
Open FreeCAD directly in the Chip-Packaging workbench.

Retries instead of activating once: FreeCAD discovers Mod/ directories on a
timer, so right after the main window appears the workbench may not be
registered yet. A single call would then succeed or fail depending on how
fast the disk is.
"""

import FreeCAD
import FreeCADGui

_WORKBENCH = {workbench!r}
_TICK_MS = 250
_LEFT = [{int(retries)}]


def _activate():
    try:
        if _WORKBENCH in FreeCADGui.listWorkbenches():
            FreeCADGui.activateWorkbench(_WORKBENCH)
            FreeCAD.Console.PrintMessage(
                "[Launcher] Chip-Packaging workbench active.\\n")
            return
    except Exception as exc:
        FreeCAD.Console.PrintWarning(f"[Launcher] {{exc}}\\n")

    _LEFT[0] -= 1
    if _LEFT[0] > 0:
        _retry()
    else:
        FreeCAD.Console.PrintWarning(
            "[Launcher] Chip-Packaging workbench did not register in time; "
            "pick it from the workbench dropdown.\\n")


def _retry():
    try:
        from PySide6 import QtCore
    except ImportError:
        from PySide2 import QtCore
    QtCore.QTimer.singleShot(_TICK_MS, _activate)


_retry()
'''


# ── Creating the .lnk ─────────────────────────────────────────────────────
# A .lnk is a COM object, so PowerShell's WScript.Shell is the shortest
# dependency-free route. The alternative — writing the binary Shell Link
# format by hand — is a great deal of code for no gain.

def _ps_quote(value: str) -> str:
    """Single-quote for PowerShell, where '' is the escaped quote."""
    return "'" + str(value).replace("'", "''") + "'"


def shortcut_script(lnk, target, arguments="", icon="", workdir="",
                    description="") -> str:
    """The PowerShell that creates (or overwrites) the .lnk."""
    lines = [
        "$ErrorActionPreference = 'Stop'",
        f"$s = (New-Object -ComObject WScript.Shell).CreateShortcut({_ps_quote(lnk)})",
        f"$s.TargetPath = {_ps_quote(target)}",
    ]
    if arguments:
        lines.append(f"$s.Arguments = {_ps_quote(arguments)}")
    if workdir:
        lines.append(f"$s.WorkingDirectory = {_ps_quote(workdir)}")
    if icon:
        # ',0' selects the first image in the file; without an index the
        # shell sometimes falls back to the target's own icon.
        lines.append(f"$s.IconLocation = {_ps_quote(str(icon) + ',0')}")
    if description:
        lines.append(f"$s.Description = {_ps_quote(description)}")
    lines.append("$s.Save()")
    lines.append("Write-Output 'OK'")
    return "\n".join(lines) + "\n"


def shortcut_arguments(macro) -> str:
    """
    The command line FreeCAD.exe is given.

    Quoted because the install path — "C:\\Program Files\\FreeCAD 1.1\\..." —
    contains spaces, and an unquoted path is parsed as several arguments and
    silently ignored.
    """
    return f'"{macro}"'


def plan(desktop=None, root=None) -> dict:
    """
    Everything the GUI layer needs to create the shortcut, resolved but not
    yet acted on — which is also what makes the decisions testable.
    """
    root = root or workbench_root()
    macro = launcher_path(root)
    exe = freecad_executable()
    return {
        "lnk": shortcut_path(desktop),
        "target": exe,
        "arguments": shortcut_arguments(macro),
        "workdir": os.path.dirname(exe),
        "icon": icon_path(root),
        "macro": macro,
        # ASCII only: this string travels through a generated .ps1 and into
        # the shell's own property store, and a non-ASCII character has
        # already bitten this workbench once via the Windows console codec.
        "description": ("FreeCAD - Chip-Packaging Workbench "
                         "(GDSII import, leadframes, wire bonding, routing)"),
    }
